import sqlite3
import json
from typing import Dict, Any, List

class TelemetryDatabase:
    def __init__(self, db_path: str = ":memory:"):
        self.conn = sqlite3.connect(db_path)
        self.conn.row_factory = sqlite3.Row
        self._create_tables()

    def _create_tables(self):
        with self.conn:
            self.conn.execute("""
                CREATE TABLE IF NOT EXISTS telemetry_records (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    run_id TEXT,
                    station_id TEXT,
                    simulation_time REAL,
                    persistence_time REAL,
                    source TEXT
                )
            """)
            self.conn.execute("""
                CREATE TABLE IF NOT EXISTS telemetry_component_states (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    record_id INTEGER,
                    component_name TEXT,
                    type TEXT,
                    status TEXT,
                    value_json TEXT,
                    FOREIGN KEY(record_id) REFERENCES telemetry_records(id)
                )
            """)
            self.conn.execute("""
                CREATE TABLE IF NOT EXISTS telemetry_connection_states (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    record_id INTEGER,
                    source_name TEXT,
                    target_name TEXT,
                    type TEXT,
                    status TEXT,
                    FOREIGN KEY(record_id) REFERENCES telemetry_records(id)
                )
            """)
            self.conn.execute("""
                CREATE TABLE IF NOT EXISTS telemetry_external_states (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    record_id INTEGER,
                    external_json TEXT,
                    FOREIGN KEY(record_id) REFERENCES telemetry_records(id)
                )
            """)
            
            # Indexes
            self.conn.execute("CREATE INDEX IF NOT EXISTS idx_record_run ON telemetry_records(run_id, simulation_time)")
            self.conn.execute("CREATE INDEX IF NOT EXISTS idx_comp_record ON telemetry_component_states(record_id)")
            self.conn.execute("CREATE INDEX IF NOT EXISTS idx_conn_record ON telemetry_connection_states(record_id)")

    def insert_telemetry_batch(self, run_id: str, station_id: str, source: str, records: List[Dict[str, Any]]):
        """
        Inserts a batch of telemetry records generated by the engine.
        Each record should have:
        {
            "time": 0.00416,
            "persistence_time": 1690000000.0,
            "components": [ ... ],
            "connections": [ ... ],
            "external": { ... }
        }
        """
        with self.conn:
            for rec in records:
                cur = self.conn.execute(
                    "INSERT INTO telemetry_records (run_id, station_id, simulation_time, persistence_time, source) VALUES (?, ?, ?, ?, ?)",
                    (run_id, station_id, rec["time"], rec.get("persistence_time", 0.0), source)
                )
                rec_id = cur.lastrowid
                
                # Insert components
                if "components" in rec:
                    self.conn.executemany(
                        "INSERT INTO telemetry_component_states (record_id, component_name, type, status, value_json) VALUES (?, ?, ?, ?, ?)",
                        [(rec_id, c.name, getattr(c, "type", ""), c.status, json.dumps(c.value)) for c in rec["components"]]
                    )
                    
                # Insert connections
                if "connections" in rec:
                    self.conn.executemany(
                        "INSERT INTO telemetry_connection_states (record_id, source_name, target_name, type, status) VALUES (?, ?, ?, ?, ?)",
                        [(rec_id, c.source, c.target, c.type, c.status) for c in rec["connections"]]
                    )
                    
                # Insert external
                if "external" in rec:
                    ext_data = rec["external"]
                    # If it's a pydantic model, convert to dict
                    if hasattr(ext_data, "model_dump"):
                        ext_data = ext_data.model_dump()
                    elif hasattr(ext_data, "dict"):
                        ext_data = ext_data.dict()
                        
                    self.conn.execute(
                        "INSERT INTO telemetry_external_states (record_id, external_json) VALUES (?, ?)",
                        (rec_id, json.dumps(ext_data))
                    )
                    
    def get_latest_record(self, run_id: str) -> Dict[str, Any]:
        cur = self.conn.execute("SELECT * FROM telemetry_records WHERE run_id = ? ORDER BY simulation_time DESC LIMIT 1", (run_id,))
        row = cur.fetchone()
        if not row: return {}
        
        rec_id = row["id"]
        
        # Fetch components
        comps = self.conn.execute("SELECT * FROM telemetry_component_states WHERE record_id = ?", (rec_id,)).fetchall()
        
        # Fetch connections
        conns = self.conn.execute("SELECT * FROM telemetry_connection_states WHERE record_id = ?", (rec_id,)).fetchall()
        
        # Fetch external
        ext = self.conn.execute("SELECT * FROM telemetry_external_states WHERE record_id = ?", (rec_id,)).fetchone()
        
        return {
            "time": row["simulation_time"],
            "components": [dict(c, value_json=json.loads(c["value_json"])) for c in comps],
            "connections": [dict(c) for c in conns],
            "external": json.loads(ext["external_json"]) if ext else {}
        }
